#users stores at vars file
---
servers:
  hosts:
    gw:
      ansible_host: 10.8.0.1
      target: '-docker_ovpn-'
    dns:
      ansible_host: 10.8.0.2
      target: '-dhcp- -dns_server- -ntp-'
    centos:
      ansible_host: 10.8.0.3
      ansible_user: root
      target: '-web-'
    deb1:
      ansible_host: 10.8.0.4
      target: '-web_proxy-'

webservers:
  hosts:
    deb2:
      ansible_host: 10.8.0.11
    deb3:
      ansible_host: 10.8.0.12

localservers:
  children:
    webservers:
    servers:

linuxservers:
  children:
    localservers:
