---
 - name: New servers routine after install
   hosts: localservers
   become: true
   become_method: su

   tasks:
#     - name: Update yum package list
#       yum:
#         update_cache: yes
#       when: ansible_facts['os_family'] == 'RedHat'
#       become: true
#       become_method: su
     - name: Perform some cool staff on Debian-based
       when: ansible_facts['os_family'] == 'Debian'
       block:
         - name: Update repo file
           copy:
             src: ./files/sources.list
             dest: /etc/apt/
           tags: update

         - name: Update apt package list
           apt:
             update_cache: yes
           tags: update

         - name: Update ntp configuration
           template:
             src: ./files/timesyncd.conf.j2
             dest: /etc/systemd/timesyncd.conf
           notify:
             - Restart systemd-ntp daemon

     - name: Add date to history
       copy:
         src: ./files/add_at_startup.sh
         dest: /etc/profile.d/
         mode: '644'
       tags: debug

     - name: Install OpenVPN Server in Docker Container
       when: target is search("-docker_ovpn-")
       block:
         - name: Update apt package list and install rsync
           apt: 
             name: rsync
             update_cache: yes
             
         - name: Install Docker.io
           apt:
             name: docker.io
           when: ansible_facts['os_family'] == 'Debian'
           
         - name: Copy src for OVPN Docker image
           synchronize:
             src: files/docker-openvpn
             dest: /home/{{ ansible_user }}
 
         - name: Create volume for OVPN container
           command: "/usr/bin/docker volume create {{ docker_ovpn_volume }}"
 
         - name: Check volume for OVPN container
           command: '/usr/bin/docker volume inspect --format \{\{.Mountpoint\}\} {{ docker_ovpn_volume }}'
           register: d_v_created
           
         - name: Volume creation result
           debug:
             msg: "Volume created at {{ d_v_created.stdout }}"
             
         - name: Create image for OVPN container
           shell: "cd /home/{{ ansible_user }}/docker-openvpn && /usr/bin/docker build . -t ovpn-image"  
           
         - name: Create OVPN container conf
           command: '/usr/bin/docker run -v {{ docker_ovpn_volume }}:/etc/openvpn --rm ovpn-image ovpn_genconfig -u {{ ansible_default_ipv4.address }}:1111 -s 192.168.16.0/24 -m 1450 -N'
         
         - name: Create to-do list 
           shell: >
             echo "You have to do a couple of operations to complete ovpn installation: \n
             1. Init PKI: \n
             docker run -v {{ docker_ovpn_volume }}:/etc/openvpn --rm -it ovpn-image ovpn_initpki \n
             2. Run container: \n
             docker run -v {{ docker_ovpn_volume }}:/etc/openvpn --name openvpn -d -p 1111:1194/udp --cap-add=NET_ADMIN --memory-swap=200m --memory=200m --cpus=0.5 ovpn-image \n
             3. Create users: \n 
             docker run -v {{ docker_ovpn_volume }}:/etc/openvpn --rm -it ovpn-image easyrsa build-client-full CLIENTNAME nopass \n
             4. Get client config: \n
             docker run -v {{ docker_ovpn_volume }}:/etc/openvpn --rm ovpn-image ovpn_getclient CLIENTNAME > CLIENTNAME.ovpn"
             > /root/ovpnto-do.list
           
     - name: Install pi-hole in Docker Container
       when: target is search("-docker_pihole-")
       block:
         - name: Update apt package list and install rsync
           apt: 
             name: rsync
             update_cache: yes
             
         - name: Install Docker.io
           apt:
             name: docker.io
             state: present
           when: ansible_facts['os_family'] == 'Debian'
           
         - name: Copy src for Docker image pihole
           synchronize:
             src: files/docker-pi-hole
             dest: /home/{{ ansible_user }}
 
         - name: Create volume for pihole container
           command: "/usr/bin/docker volume create {{ docker_pihole_volume }}"
 
         - name: Check volume for pihole container
           command: '/usr/bin/docker volume inspect --format \{\{.Mountpoint\}\} {{ docker_pihole_volume }}'
           register: d_p_created
           
         - name: Volume creation result
           debug:
             msg: "Volume created at {{ d_p_created.stdout }}"
             
         - name: Create image for pihole container
           shell: "cd /home/{{ ansible_user }}/docker-pi-hole/src && /usr/bin/docker build . -t my:pi-hole" 

         - name: Check if pihole net is exist
           command: '/usr/bin/docker network ls --format \{\{.Name\}\}'
           register: d_n_running

         - name: Create network for pihole container
           command: "/usr/bin/docker network create --subnet=172.18.0.0/30 pi-net"
           when: d_n_running is not search("pi-net")

         - name: Check if pihole container is running
           command: '/usr/bin/docker ps -a --format \{\{.Names\}\}'
           register: d_p_running
           
         - name: Stop and remove pihole container
           shell: '/usr/bin/docker stop pihole && /usr/bin/docker rm pihole'
           when: d_p_running is search("pihole")

         - name: Create container for pihole container
           command: '/usr/bin/docker run -d --name pihole -v "{{ d_p_created.stdout }}/etc-pihole:/etc/pihole"
                    -v "{{ d_p_created.stdout }}/etc-dnsmasq.d:/etc/dnsmasq.d" --dns={{ default_ext_dns }}
                    --hostname=pi.hole -e FTLCONF_LOCAL_IPV4="127.0.0.1" -e WEBPASSWORD="kekme"
                    -e PIHOLE_DNS="{{ default_ext_dns }}" --net=pi-net --ip="172.18.0.2" --memory-swap=200m
                    --memory=200m --cpus=0.5 my:pi-hole'
           
     - name: Install nginx
       when: target is search("-web-")
       block:
         - name: Install nginx on Debian
           apt:
             name: nginx
           when: ansible_facts['os_family'] == 'Debian'
           
         - name: Install nginx on Centos
           yum:
             name: nginx
             state: present
           when: ansible_facts['os_family'] == 'RedHat'
           
         - name: Creating directory for content
           file:
             path: /var/www/testme
             state: directory
             mode: '0755'
             
         - name: Copy content
           copy:
             src: ./files/site_testme/index.html
             dest: /var/www/testme/index.html
             mode: '0755'

         - name: Copy conf file for web
           template:
             src: ./files/nginx.conf.j2
             dest: /etc/nginx/nginx.conf
             mode: '0755'

         - name: Start nginx service
           systemd_service:
             name: nginx
             state: started
             daemon_reload: true
             enabled: true
             
         - name: Add iptables rules for nx
           iptables:
             chain: INPUT
             comment: This rules is for access to web server
             protocol: tcp
             destination_ports:
               - "22"
               - "80"
               - "443"
             jump: ACCEPT
             
     - name: Install nginx proxy
       when: target is search("-web_proxy-")
       block:
         - name: Install nginx proxy on Debian
           apt:
             name: nginx
           when: ansible_facts['os_family'] == 'Debian'
           
         - name: Install nginx proxy on Centos
           yum:
             name: nginx
             state: present
           when: ansible_facts['os_family'] == 'RedHat'
           
         - name: Copy conf file for web-proxy
           template:
             src: ./files/nginx_proxy_upstream.conf.j2
             dest: /etc/nginx/nginx.conf
             mode: '0755'

         - name: Start nginx proxy service
           systemd_service:
             name: nginx
             state: started
             daemon_reload: true
             enabled: true
             
         - name: Add iptables rules for nginx proxy
           iptables:
             chain: INPUT
             comment: This rules is for access to web server
             protocol: tcp
             destination_ports:
               - "22"
               - "80"
               - "443"
             jump: ACCEPT
         
     - name: NTP Server Setup
       when: target is search("-ntp-")
       block:
         - name: Install NTP Server
           apt:
             name: ntp
            # state: present
#         - name: Add firewall rules
#           iptables:
#             chain: INPUT
#             protocol: udp
#             destination_port: '123'
#             jump: ACCEPT
         - name: Creating log folder
           file:
             path: /var/log/ntpsec
             state: directory
             mode: '0755'
             group: ntpsec
             owner: ntpsec
         - name: Copy NTP configuration
           template:
             src: ./files/ntp.conf.j2
             dest: /etc/ntpsec/ntp.conf
             mode: '0644'   
           notify: 
             - Restart ntp server daemon
             - Check time synq
             - Output time synq
         
       tags: sdebug 
     - name: DNS Server Setup
       when: target is search("-dns_server-")
       block:
         - name: Gather the package facts
           ansible.builtin.package_facts:
             manager: auto
             
         - name: Remove wrong version pkg  
           apt: "name={{ item }} state=absent"
           loop: 
            - bind9-utils
            - bind9-libs
           when: "'bind9' not in ansible_facts.packages"
           
         - name: Install Bind9  
           apt:
             name: bind9
             state: present
#         - name: Add firewall rules
#           iptables:
#             chain: INPUT
#             protocol: udp
#             destination_port: '123'
#             jump: ACCEPT
         - name: Creating master-zone folder
           file:
             path: /var/lib/bind/master-zones
             state: directory
             group: bind
             mode: '0775'
             
         - name: Copy static configuration files
           copy:
             src : "{{ item.src }}"
             dest: /etc/bind/
           loop:
             - src: ./files/dns/named.conf

         - name: Copy dynamic configuration files
           template:
             src: "{{ item.src }}"
             dest: "{{ item.dest }}"
           loop: 
             - src: ./files/dns/named.conf.local.j2
               dest: /etc/bind/named.conf.local
             - src: ./files/dns/template.zone.j2
               dest: "/var/lib/bind/master-zones/{{ dns_domain }}.zone"
             - src: ./files/dns/0.8.10.zone
               dest: /var/lib/bind/master-zones/0.8.10.zone
             - src: ./files/dns/resolv.conf.j2
               dest: /etc/resolv.conf
           notify: Restart DNS server daemon
           
         - name: Check DNS configuration
           command: 'named-checkconf -z'
           register: resultdns
           
         - name: Out result
           debug: 
             msg: "{{ resultdns }}"
       tags: sdebug 

     - name: DHCP Server Setup
       when: target is search("-dhcp-")
       block:
         - name: Gather the package facts
           ansible.builtin.package_facts:
             manager: auto
           
         - name: Install DHCP Server  
           apt:
             name: isc-dhcp-server
             state: present
             
#         - name: Add firewall rules
#           iptables:
#             chain: INPUT
#             protocol: udp
#             destination_port: '123'
#             jump: ACCEPT
         - name: Copy files if DNS-server is installed
           when: "'bind9' in ansible_facts.packages"
           block:
             - name: Create dir for dynamic update key
               file:
                 path: /etc/dhcp/ddns-keys
                 state: directory
             
             - name: Copy configuration file 2
               template:
                 src: ./files/dhcpd_w_dns.conf.j2
                 dest: /etc/dhcp/dhcpd.conf
                   
             - name: Copy DNS key for dynamic update
               command: "cp /etc/bind/rndc.key /etc/dhcp/ddns-keys/"
         
         - name: Copy files if DNS-server is not installed
           when: "'bind9' not in ansible_facts.packages"
           template:
             src: ./files/dhcpd_wo_dns.conf.j2
             dest: /etc/dhcp/dhcpd.conf
             
         - name: Copy common DHCP configuration file
           template:
             src: ./files/isc-dhcp-server.j2
             dest: /etc/default/isc-dhcp-server
           notify: Restart DHCP server daemon
                             
       tags: sdebug 
       
   handlers:
    - name: Restart systemd-ntp daemon
      ansible.builtin.systemd:
        name: systemd-timesyncd
        daemon-reload: true
        enabled: true
        state: restarted
        
    - name: Restart ntp server daemon
      ansible.builtin.systemd:
        name: ntp
        #daemon-reload: true
        enabled: true
        state: restarted
        
    - name: Check time synq
      command: 'ntpq -p'
      register: chtimeresult
      
    - name: Output time synq
      debug: 
        msg: "{{ chtimeresult }}"   
        
    - name: Restart DNS server daemon
      ansible.builtin.systemd:
        name: named
        daemon-reload: true
        enabled: true
        state: restarted

    - name: Restart DHCP server daemon
      ansible.builtin.systemd:
        name: isc-dhcp-server
        daemon-reload: true
        enabled: true
        state: restarted
